### ISSUE TITLE
"Ambiguous reference to member 'appendInterpolation'" error

### ISSUE THREAD

**Issue by markmals** [mxcl/Chalk#1]
I'm getting an `Ambiguous reference to member 'appendInterpolation'` compile-time error when trying to use Chalk with either a variable or a string literal.

```swift
import Chalk

print("\("Hello, world!", style: .bold)")
        ^ Ambiguous reference to member 'appendInterpolation'

let greeting = "Hello, world!"
print("\(greeting, style: .bold)")
        ^ Ambiguous reference to member 'appendInterpolation'
```

This happens with any Chalk parameters used in any string interpolation in my project. I'm experiencing this issue in a complex project, but have also verified it to be an issue in a brand new blank project generated with `swift package init --type executable`.

Using Xcode version 10.2 (10E125) and Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) with the package dependency `.package(url: "https://github.com/mxcl/Chalk", from: "0.3.0")`.

**Comment by mxcl** [comment]
Cannot reproduce, can you provide a test case?

**Comment by mxcl** [comment]
Oh ok, this is easy, we don’t provide that overload, you have to provide a `color`.

**Comment by mxcl** [comment]
PR welcome if this is something you want fixed.

**Comment by markmals** [comment]
Okay 👍🏼 Never mind, I'll go back to using Rainbow.
