### ISSUE TITLE
Detecting non-interactive terminals

### ISSUE THREAD

**Issue by mickeyl** [mxcl/Chalk#6]
I've been previously using a competitor's project that detects the terminal type and can transparently turn off color and style coding when it encounters a non-interactive one (e.g., file redirection).

Since I like the Chalk API much better, it would be cool, if it could do something equivalent.

**Comment by mxcl** [comment]
I believe I originally considered this “out of scope” but let’s face it, there needs to be an easy way to do this.

Not sure about how it should work though.
